#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"
if [[ -f .tools/cuda-env.sh ]]; then
  # Generated by scripts/setup_cuda_runfile_user.sh. Kept outside public sync.
  # shellcheck disable=SC1091
  source .tools/cuda-env.sh
fi
rm -rf .lab_tmp reports
mkdir -p .lab_tmp reports
exec > >(tee reports/run_lab_output.txt) 2>&1

printf 'lab=hardware-bottleneck-foundations\n'
printf 'pwd=%s\n' "$PWD"
printf 'cc=%s\n' "$(command -v gcc || true)"
printf 'python=%s\n' "$(python3 --version)"
printf 'kernel=%s\n' "$(uname -srmo)"
printf 'nvcc=%s\n' "$(command -v nvcc || true)"
printf 'cuda_arch_flags=%s\n' "${CUDA_ARCH_FLAGS:-}"

if ! command -v gcc >/dev/null 2>&1; then
  echo 'gcc not found; install build-essential or gcc to run the CPU benchmark.' >&2
  exit 2
fi

printf '\ncompile CPU benchmark\n'
gcc -std=c11 -O2 -fno-tree-vectorize -fno-if-conversion -Wall -Wextra -Wpedantic -Werror \
  src/hardware_bottleneck_lab.c \
  -o .lab_tmp/hardware_bottleneck_lab

printf '\nrun CPU benchmark\n'
./.lab_tmp/hardware_bottleneck_lab | tee reports/raw_metrics.csv

printf '\noptional CUDA transfer/timing probe\n'
if command -v nvcc >/dev/null 2>&1; then
  set +e
  nvcc_flags=(-O2)
  if [[ -n "${CUDA_ARCH_FLAGS:-}" ]]; then
    # Intentionally split a simple flag string such as "-arch=native" or "-gencode arch=compute_120,code=sm_120".
    read -r -a extra_nvcc_flags <<< "${CUDA_ARCH_FLAGS}"
    nvcc_flags+=("${extra_nvcc_flags[@]}")
  fi
  printf 'nvcc_compile_flags=%s\n' "${nvcc_flags[*]}" | tee reports/cuda_compile_command.txt
  nvcc "${nvcc_flags[@]}" src/cuda_transfer_probe.cu -o .lab_tmp/cuda_transfer_probe > reports/cuda_compile.log 2>&1
  compile_rc=$?
  set -e
  if [[ "$compile_rc" -eq 0 ]]; then
    set +e
    ./.lab_tmp/cuda_transfer_probe > reports/cuda_transfer_report.json 2> reports/cuda_transfer_stderr.txt
    run_rc=$?
    set -e
    if [[ "$run_rc" -ne 0 ]]; then
      python3 - <<'PY'
import json
from pathlib import Path
Path('reports/cuda_transfer_report.json').write_text(json.dumps({
  'status': 'run_failed',
  'reason': Path('reports/cuda_transfer_stderr.txt').read_text(encoding='utf-8', errors='replace')[:4000]
}, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
PY
    fi
  else
    python3 - <<'PY'
import json
from pathlib import Path
Path('reports/cuda_transfer_report.json').write_text(json.dumps({
  'status': 'compile_failed',
  'reason': Path('reports/cuda_compile.log').read_text(encoding='utf-8', errors='replace')[:4000]
}, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
PY
  fi
else
  python3 - <<'PY'
import json
from pathlib import Path
Path('reports/cuda_transfer_report.json').write_text(json.dumps({
  'status': 'skipped',
  'reason': 'nvcc not found; CPU cache/branch experiments still ran. Install CUDA toolkit if you want host/device transfer timing.'
}, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
PY
fi
cat reports/cuda_transfer_report.json

printf '\nbuild learner report\n'
python3 scripts/report.py reports/raw_metrics.csv reports/cuda_transfer_report.json reports/report.json reports/report.md

printf '\nrun tests\n'
python3 -m unittest discover -s tests -v

printf '\nvisible result markers\n'
printf 'raw_metrics_ready=reports/raw_metrics.csv\n'
printf 'report_json_ready=reports/report.json\n'
printf 'report_md_ready=reports/report.md\n'
printf 'hardware_bottleneck_lab_status=ok\n'
