#!/usr/bin/env python3
from __future__ import annotations

import csv
import json
import sys
from pathlib import Path


def load_csv(path: Path) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    with path.open(newline='', encoding='utf-8') as f:
        for row in csv.DictReader(f):
            rows.append({
                'experiment': row['experiment'],
                'variant': row['variant'],
                'work_items': int(row['work_items']),
                'useful_bytes': int(row['useful_bytes']),
                'seconds': float(row['seconds']),
                'mib_per_s': float(row['mib_per_s']),
                'checksum': float(row['checksum']),
            })
    return rows


def by_variant(rows: list[dict[str, object]], experiment: str, variant: str) -> dict[str, object]:
    for row in rows:
        if row['experiment'] == experiment and row['variant'] == variant:
            return row
    raise KeyError((experiment, variant))


def ratio(numerator: float, denominator: float) -> float | None:
    if denominator == 0:
        return None
    return numerator / denominator


def load_cuda(path: Path) -> dict[str, object]:
    if not path.exists():
        return {'status': 'missing'}
    return json.loads(path.read_text(encoding='utf-8'))


def build_report(raw_rows: list[dict[str, object]], cuda: dict[str, object]) -> dict[str, object]:
    row = by_variant(raw_rows, 'matrix_locality', 'row_major')
    col = by_variant(raw_rows, 'matrix_locality', 'column_major')
    branch_p = by_variant(raw_rows, 'branch_predictability', 'predictable_even')
    branch_u = by_variant(raw_rows, 'branch_predictability', 'unpredictable_lcg')
    stride_rows = [r for r in raw_rows if r['experiment'] == 'stride_scan']
    stride_rows.sort(key=lambda r: int(str(r['variant']).split('_')[1]))
    return {
        'schema_version': 1,
        'cpu': {
            'raw_rows': raw_rows,
            'matrix_column_to_row_seconds_ratio': ratio(float(col['seconds']), float(row['seconds'])),
            'branch_unpredictable_to_predictable_seconds_ratio': ratio(float(branch_u['seconds']), float(branch_p['seconds'])),
            'stride_scan': stride_rows,
            'interpretation_boundary': 'Ratios are local measurements on this machine. They show bottleneck direction, not a portable benchmark score.'
        },
        'cuda': cuda,
        'learning_claims': [
            'Row-major scans tend to exploit spatial locality better than column-major scans in row-major C arrays.',
            'Large strides reduce useful bytes per cache line and usually lower useful-byte throughput.',
            'Unpredictable branches may cost more than predictable branches, but compilers and CPUs can change the exact ratio.',
            'CUDA transfer timing must be separated from kernel timing before claiming a kernel optimization helped an end-to-end task.'
        ]
    }


def render_markdown(report: dict[str, object]) -> str:
    cpu = report['cpu']
    lines: list[str] = [
        '# Hardware bottleneck foundations report',
        '',
        'This report is generated by `run_lab.sh`. It is evidence from the local machine, not a universal hardware benchmark.',
        '',
        '## CPU summary',
        '',
        f"- Matrix column/row seconds ratio: `{cpu['matrix_column_to_row_seconds_ratio']:.3f}`",
        f"- Branch unpredictable/predictable seconds ratio: `{cpu['branch_unpredictable_to_predictable_seconds_ratio']:.3f}`",
        '',
        '## Raw CPU rows',
        '',
        '| experiment | variant | useful MiB/s | seconds | useful bytes |',
        '| --- | --- | ---: | ---: | ---: |',
    ]
    for row in cpu['raw_rows']:
        lines.append(f"| {row['experiment']} | {row['variant']} | {row['mib_per_s']:.1f} | {row['seconds']:.6f} | {row['useful_bytes']} |")
    lines.extend(['', '## How to read this', ''])
    lines.append('- If `column/row` is greater than 1, the same arithmetic became slower mainly because the access order fought the row-major memory layout.')
    lines.append('- If high strides have much lower useful MiB/s, the CPU fetched cache lines but your program used only a small part of each line.')
    lines.append('- If unpredictable branches are slower, the control path became part of the bottleneck; do not blame only arithmetic count.')
    lines.append('- If CUDA is skipped, the CPU part still teaches the memory/control-flow model needed before GPU timing.')
    lines.extend(['', '## CUDA transfer/timing status', ''])
    cuda = report['cuda']
    lines.append(f"Status: `{cuda.get('status')}`")
    if cuda.get('status') == 'ok':
        lines.append(f"Device: `{cuda.get('device')}`")
        if cuda.get('timing_note'):
            lines.append(f"Timing note: `{cuda.get('timing_note')}`")
        lines.append('Compare copy and kernel rows only within the same run; the values are local measurements, not portable benchmark scores.')
        lines.extend(['', '| bytes | pageable H2D ms | pageable D2H ms | pinned H2D ms | pinned D2H ms | kernel ms |', '| ---: | ---: | ---: | ---: | ---: | ---: |'])
        for row in cuda.get('rows', []):
            lines.append(f"| {row['bytes']} | {row['pageable_h2d_ms']:.4f} | {row['pageable_d2h_ms']:.4f} | {row['pinned_h2d_ms']:.4f} | {row['pinned_d2h_ms']:.4f} | {row['kernel_ms']:.4f} |")
    else:
        lines.append(f"Reason: `{cuda.get('reason', 'not provided')}`")
    lines.extend(['', '## Boundary', '', str(cpu['interpretation_boundary']), ''])
    return '\n'.join(lines)


def main(argv: list[str]) -> int:
    if len(argv) != 5:
        print('usage: report.py RAW_CSV CUDA_JSON REPORT_JSON REPORT_MD', file=sys.stderr)
        return 2
    raw_csv, cuda_json, report_json, report_md = map(Path, argv[1:])
    rows = load_csv(raw_csv)
    cuda = load_cuda(cuda_json)
    report = build_report(rows, cuda)
    report_json.write_text(json.dumps(report, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    report_md.write_text(render_markdown(report), encoding='utf-8')
    print('REPORT_JSON=' + str(report_json))
    print('REPORT_MD=' + str(report_md))
    print('MATRIX_COLUMN_TO_ROW_RATIO={:.3f}'.format(report['cpu']['matrix_column_to_row_seconds_ratio']))
    print('BRANCH_UNPREDICTABLE_TO_PREDICTABLE_RATIO={:.3f}'.format(report['cpu']['branch_unpredictable_to_predictable_seconds_ratio']))
    print('CUDA_STATUS=' + str(cuda.get('status')))
    print('RUN_STATUS=ok')
    return 0


if __name__ == '__main__':
    raise SystemExit(main(sys.argv))
